name: Deployment pipeline

on:
 push:
  branches:
   - main

 pull_request:
  branches:
   - main
  types:
   - opened
   - synchronize

jobs:
 simple_deployment_pipeline:
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
       node-version: "20"

    - name: install dependencies
      run: npm install

    - name: check style
      run: npm run eslint

    - name: trigger deployment
      # the github.event_name will be 'push' if the pull_request is merged.
      if: ${{ github.event_name == 'push' }}
      run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_KEY_ID}}


    
 tag_release:
  needs: [simple_deployment_pipeline]
  runs-on: ubuntu-20.04
  
  steps:
   - name: Bump version and push tag
     if: ${{ github.event_name == 'push' }} 
     #setup repo
     uses: actions/checkout@v4
     uses: anothrNick/github-tag-action@1.71.0
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WITH_V: true
      PRERELEASE: true
      DEFAULT_BUMP: patch